config/routes.rb
Fandangr::Application.routes.draw do
  resources :films

  get "login" => 'sessions#new', :as => :login
  post "create_session" => 'sessions#create', :as => :create_session

  root :to => "static_pages#home"

end

app/models/film.rb
class Film < ActiveRecord::Base
  attr_accessible :title, :poster

  has_many :showings

  mount_uploader :poster, ImageUploader
end

app/models/showing.rb
class Showing < ActiveRecord::Base
  attr_accessible :film_id, :showing_on

  has_many :tickets
  belongs_to :film

  def available_tickets?
    unreserved_tickets = self.tickets.where(:user_id => nil)

    unreserved_tickets.length > 0
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :showing_id, :seat

  belongs_to :user
  belongs_to :showing

  def available?
    self.user.blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password, :password_confirmation

  validates_uniqueness_of :email

  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  # GET /films
  # GET /films.json
  def index
    @films = Film.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @films }
    end
  end

  # GET /films/1
  # GET /films/1.json
  def show
    @film = Film.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @film }
    end
  end

  # GET /films/new
  # GET /films/new.json
  def new
    @film = Film.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @film }
    end
  end

  # GET /films/1/edit
  def edit
    @film = Film.find(params[:id])
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(params[:film])

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render json: @film, status: :created, location: @film }
      else
        format.html { render action: "new" }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /films/1
  # PUT /films/1.json
  def update
    @film = Film.find(params[:id])

    respond_to do |format|
      if @film.update_attributes(params[:film])
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film = Film.find(params[:id])
    @film.destroy

    respond_to do |format|
      format.html { redirect_to films_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:user][:email])

    if user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to root_path, :notice => "Logged in!"
    else
      raise "No log in succeeded :("
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/films/_form.html.erb
<%= form_for(@film, :html_options => {:multipart => true}) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% @film.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :poster %>
    <%= f.file_field :poster %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render 'form' %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<h1>Listing films</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @films.each do |film| %>
  <tr>
    <td><%= link_to 'Show', film %></td>
    <td><%= link_to 'Edit', edit_film_path(film) %></td>
    <td><%= link_to 'Destroy', film, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Film', new_film_path %>

app/views/films/new.html.erb
<h1>New film</h1>

<%= render 'form' %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @film.title %></h1>

<p><%= image_tag @film.poster %></p>

<%= link_to 'Edit', edit_film_path(@film) %> |
<%= link_to 'Back', films_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fandangr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p><%= flash.notice %></p>

  <%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>